//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaturamentoDiretoRevenda.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteComplemtentar
    {
        public int Id { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string WebSite { get; set; }
        public string EmailNF { get; set; }
        public Nullable<int> IdCondicaoPagto { get; set; }
        public string Desconto { get; set; }
        public string LimiteCredito { get; set; }
        public string ObservacaoGeral { get; set; }
        public string ObservacaoFaturamento { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<System.DateTime> DataUltimaAlteracao { get; set; }
        public Nullable<bool> Ativo { get; set; }
    
        public virtual ClienteIdentificacao ClienteIdentificacao { get; set; }
    }
}
