//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaturamentoDiretoRevenda.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteFolowUp
    {
        public int Id { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string Descricao { get; set; }
        public string Pessoa { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<bool> Ativo { get; set; }
    
        public virtual ClienteIdentificacao ClienteIdentificacao { get; set; }
    }
}
