//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaturamentoDiretoRevenda.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int Id { get; set; }
        public Nullable<int> IdRevenda { get; set; }
        public string Codigo { get; set; }
        public string PartNumber { get; set; }
        public string Descricao { get; set; }
        public string DescricaoNF { get; set; }
        public string Unidade { get; set; }
        public string PesoBruto { get; set; }
        public string PesoLiquido { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<int> IdTipoProduto { get; set; }
        public string Moeda { get; set; }
        public string PrecoCompra { get; set; }
        public Nullable<int> Lucratividade { get; set; }
        public string DescricaoCompleta { get; set; }
        public string ClassificacaoFiscal { get; set; }
        public string SituaçãoTributaria { get; set; }
        public string CatergoriaICMS { get; set; }
        public string Fornecedores { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<bool> Ativo { get; set; }
    
        public virtual Revenda Revenda { get; set; }
    }
}
